# Generated by Django 4.1 on 2022-09-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_cuisine_public_uuid_alter_item_public_uuid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_content_type',
            new_name='cart_item_content_type',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_object_id',
            new_name='cart_item_object_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='paid_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reviews', to='restaurants.item'),
        ),
    ]
