# Generated by Django 4.1 on 2022-09-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_item_content_type_orderitem_cart_item_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_item_content_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_item_object_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='restaurants.itemvariation'),
            preserve_default=False,
        ),
    ]
