# Generated by Django 4.1 on 2022-09-28 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_orderitem_cart_item_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
