# Generated by Django 4.1 on 2022-09-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_order_public_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'item')},
        ),
    ]
