# Generated by Django 4.1 on 2022-12-16 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_orderitem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
