# Generated by Django 4.1 on 2022-12-16 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_orderitem_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
