# Generated by Django 4.1 on 2022-12-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_alter_item_cuisine_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='paid_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
