# Generated by Django 4.1 on 2023-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_order_user_order_user_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='table_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
