# Generated by Django 4.1 on 2023-01-12 19:45

from django.db import migrations, models
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0005_auto_20221004_0004'),
        ('restaurants', '0018_alter_restaurant_table_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='info',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_location', to='restaurants.restaurantlocation'),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='city',
            field=iranian_cities.fields.CityField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.city'),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='province',
            field=iranian_cities.fields.ProvinceField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province'),
        ),
    ]
