# Generated by Django 4.1 on 2023-01-12 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_remove_restaurant_info_restaurant_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_restaurant', to='restaurants.restaurantlocation'),
        ),
    ]
