# Generated by Django 4.1 on 2023-01-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0025_order_alter_dineinorder_order_orderitem'),
        ('delivery', '0009_alter_deliverycart_unique_together_and_more'),
        ('restaurants', '0021_remove_order_user_remove_order_user_payment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
