# Generated by Django 4.1 on 2022-09-17 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddressinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_discounts', to='restaurants.itemvariation'),
        ),
        migrations.AddField(
            model_name='deliverycartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='delivery.deliverycart'),
        ),
        migrations.AddField(
            model_name='deliverycartitem',
            name='discount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_items', to='delivery.discount'),
        ),
        migrations.AddField(
            model_name='deliverycartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_carts', to='restaurants.itemvariation'),
        ),
        migrations.AddField(
            model_name='deliverycart',
            name='discounts',
            field=models.ManyToManyField(related_name='discount_carts', to='delivery.discount'),
        ),
        migrations.AddField(
            model_name='deliverycart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverycart',
            name='user_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_cart', to='delivery.useraddressinfo'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_delivery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deliverycartitem',
            unique_together={('item', 'cart')},
        ),
    ]
