# Generated by Django 4.1 on 2022-09-20 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_orderitem_cart_item_content_type_and_more'),
        ('delivery', '0003_alter_deliverycartitem_public_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_deliveries', to='restaurants.itemvariation'),
        ),
    ]
