# Generated by Django 4.1 on 2022-12-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_deliverycartitem_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddressinfo',
            options={'verbose_name_plural': 'User Address Info'},
        ),
    ]
