# Generated by Django 4.1 on 2022-12-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryman_delete_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverycart',
            name='paid',
        ),
    ]
