# Generated by Django 4.1 on 2023-01-15 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('azbankgateways', '0004_auto_20211115_1500'),
        ('restaurants', '0021_remove_order_user_remove_order_user_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0007_remove_deliverycart_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverycart',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverycart',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cart', to='restaurants.order'),
        ),
        migrations.AddField(
            model_name='deliverycart',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_cart', to='azbankgateways.bank'),
        ),
        migrations.AlterField(
            model_name='deliverycart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='deliverycart',
            unique_together={('user', 'order')},
        ),
    ]
