# Generated by Django 4.1 on 2023-01-15 17:36

from django.db import migrations, models
import django.db.models.deletion
import iranian_cities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('iranian_cities', '0005_auto_20221004_0004'),
        ('delivery', '0009_alter_deliverycart_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycart',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_carts', to='delivery.useraddressinfo'),
        ),
        migrations.AlterField(
            model_name='useraddressinfo',
            name='city',
            field=iranian_cities.fields.CityField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.city'),
        ),
        migrations.AlterField(
            model_name='useraddressinfo',
            name='province',
            field=iranian_cities.fields.ProvinceField(on_delete=django.db.models.deletion.CASCADE, to='iranian_cities.province'),
        ),
    ]
