# Generated by Django 4.1 on 2023-01-19 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_deliverycart_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycart',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.UUID('99da548f-f040-403f-8634-314af3d287b4'), unique=True),
        ),
    ]
