# Generated by Django 4.1 on 2023-01-19 23:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_alter_deliverycart_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycart',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.UUID('7d6b501b-2bb8-4f2b-b92e-656d8aa33379'), unique=True),
        ),
    ]
