# Generated by Django 4.1 on 2023-01-19 23:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_alter_deliverycart_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycart',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.UUID('378b18db-8f3b-48cd-aaaf-2c3874513b51'), unique=True),
        ),
    ]
