# Generated by Django 4.1 on 2023-01-19 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_alter_deliverycart_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycart',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.UUID('658d5bef-54e4-4683-9a74-f635d28bff67'), unique=True),
        ),
    ]
