# Generated by Django 4.1 on 2023-01-19 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_alter_deliverycart_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycart',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.UUID('1a6373e7-c3bc-4748-8c4e-258bc42feda4'), unique=True),
        ),
    ]
