# Generated by Django 4.1 on 2023-01-22 10:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0016_alter_deliverycart_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycart',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.UUID('bb24526b-fc46-46b2-9aef-b8e5fb52c445'), unique=True),
        ),
    ]
