# Generated by Django 4.1 on 2023-02-05 23:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_squashed_0028_alter_deliverycart_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycart',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deliverycart',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
