# Generated by Django 4.1 on 2022-09-17 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
    ]
