# Generated by Django 4.1 on 2022-09-19 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_rename_item_content_type_orderitem_cart_item_content_type_and_more'),
        ('in_place', '0005_alter_staff_public_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inplacecartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_inplace_cart_items', to='restaurants.itemvariation'),
        ),
    ]
