# Generated by Django 4.1 on 2022-09-28 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0008_alter_staff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inplacecartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='inplacecartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='InPlaceCart',
        ),
        migrations.DeleteModel(
            name='InPlaceCartItem',
        ),
    ]
