# Generated by Django 4.1 on 2022-10-14 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0010_alter_staff_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('delete_orders', 'is authorized to delete order records.'), ('read_salaries', "is authorized to read other staff's salaries")]},
        ),
    ]
