# Generated by Django 4.1 on 2022-10-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_order_done'),
        ('in_place', '0011_alter_staff_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DineInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_dinein', to='restaurants.order')),
            ],
        ),
    ]
