# Generated by Django 4.1 on 2022-10-19 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0013_dineinorder_public_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinorder',
            name='public_uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
