# Generated by Django 4.1 on 2022-10-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0014_alter_dineinorder_public_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='income',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
