# Generated by Django 4.1 on 2022-10-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0015_staff_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
