# Generated by Django 4.1 on 2022-11-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0018_alter_staff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
