# Generated by Django 4.1 on 2022-11-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0019_staff_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
