# Generated by Django 4.1 on 2022-12-24 00:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0020_alter_staff_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinorder',
            name='table_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
