# Generated by Django 4.1 on 2022-12-24 01:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0022_alter_dineinorder_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dineinorder',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
