# Generated by Django 4.1 on 2022-12-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0023_alter_dineinorder_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('ca', 'cashier'), ('ch', 'chef'), ('s', 'supplier'), ('w', 'waiter'), ('m', 'manager'), ('d', 'driver')], max_length=2),
        ),
    ]
