# Generated by Django 4.1 on 2023-01-15 14:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_remove_order_user_remove_order_user_payment_and_more'),
        ('delivery', '0009_alter_deliverycart_unique_together_and_more'),
        ('in_place', '0024_alter_staff_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('done', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_type', models.CharField(choices=[('d', 'delivery'), ('i', 'dine-in')], max_length=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_number', models.PositiveIntegerField(blank=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cart', to='delivery.deliverycart')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_orders', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='dineinorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_dinein', to='in_place.order'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('paid_price', models.PositiveIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_orders', to='restaurants.itemvariation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='in_place.order')),
            ],
            options={
                'unique_together': {('order', 'item')},
            },
        ),
    ]
