# Generated by Django 4.1 on 2023-01-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0025_order_alter_dineinorder_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dineinorder',
            name='description',
        ),
    ]
