# Generated by Django 4.1 on 2023-01-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_place', '0026_remove_dineinorder_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('delete_orders', 'is authorized to delete order records'), ('read_salaries', "is authorized to read other staff's salaries"), ('read_staff', 'has access to details of the staff'), ('mod_staff', 'can add, modify, or delete members for the staff'), ('edit_restaurant', 'can modify the restaurant'), ('add_items', 'can add items to the restaurant'), ('edit_items', 'can edit items of the restaurant'), ('delete_items', 'can delete items of the restaurant'), ('edit_staff', 'can edit other staff')]},
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('ca', 'cashier'), ('ch', 'chef'), ('s', 'supplier'), ('w', 'waiter'), ('m', 'manager')], max_length=2),
        ),
    ]
